# Generated by Django 5.0.7 on 2024-08-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0007_comment_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_provided',
            field=models.BooleanField(default=True),
        ),
    ]
