# Generated by Django 5.0.7 on 2024-08-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_website', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
